
POST http://127.0.0.1:5000/graph/johnson
Content-Type: application/json

{
  "nodes": [
    {
      "id": 1743691595728,
      "x": 105.96353149414062,
      "y": 166.36458206176758,
      "name": "a",
      "color": "#ff0000"
    },
    {
      "id": 1743691599287,
      "x": 195.96353149414062,
      "y": 160.36458206176758,
      "name": "b",
      "color": "#ff0000"
    },
    {
      "id": 1743691602540,
      "x": 271.9635314941406,
      "y": 102.36458206176758,
      "name": "c",
      "color": "#ff0000"
    },
    {
      "id": 1743691606027,
      "x": 282.9635314941406,
      "y": 198.36458206176758,
      "name": "d",
      "color": "#ff0000"
    },
    {
      "id": 1743691609877,
      "x": 383.9635314941406,
      "y": 169.36458206176758,
      "name": "e",
      "color": "#ff0000"
    },
    {
      "id": 1743691612345,
      "x": 450.0,
      "y": 250.0,
      "name": "f",
      "color": "#ff0000"
    },
    {
      "id": 1743691615678,
      "x": 550.0,
      "y": 200.0,
      "name": "g",
      "color": "#ff0000"
    }
  ],
  "edges": [
    {
      "node1": {
        "name": "a"
      },
      "node2": {
        "name": "b"
      },
      "weight": 1
    },
    {
      "node1": {
        "name": "b"
      },
      "node2": {
        "name": "c"
      },
      "weight": 2
    },
    {
      "node1": {
        "name": "b"
      },
      "node2": {
        "name": "d"
      },
      "weight": 3
    },
    {
      "node1": {
        "name": "c"
      },
      "node2": {
        "name": "d"
      },
      "weight": 9
    },
    {
      "node1": {
        "name": "c"
      },
      "node2": {
        "name": "e"
      },
      "weight": 3
    },
    {
      "node1": {
        "name": "d"
      },
      "node2": {
        "name": "f"
      },
      "weight": 2
    },
    {
      "node1": {
        "name": "e"
      },
      "node2": {
        "name": "g"
      },
      "weight": 5
    },
    {
      "node1": {
        "name": "f"
      },
      "node2": {
        "name": "g"
      },
      "weight": 4
    }
  ]
}
